---
title: "c-rb-classification"
author: "vk"
date: "2026-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(terra)
library(rpart)
library(rpart.plot)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tree)
```

```{r reading in chambal data and processing}
texture <- read.csv('/Users/vedikakalra/Documents/WCT/CCF Hydrology Data/Chambal/c-maps/c-sand-training-m22-texture.csv')
texture <- texture%>%
  select(-".geo", -"system.index")
texture$class <- factor(texture$class,
                        levels = c(1,2,3,4,5,6),
                    labels = c("Fresh Sand", "Sand Mining", "Wet Sand", "Fallow", "Veg Sand", "Bedrock"))
```

```{r reading in son data and processing}
son <- read.csv('/Users/vedikakalra/Documents/WCT/CCF Hydrology Data/Son/s-sand-training-m22.csv')
son <- son%>%
  select(-".geo", -"system.index")
son$class <- factor(son$class,
                    levels = c(1,2,3,4,5,6),
                    labels = c("Fresh Sand", "Sand Mining", "Wet Sand", "Fallow", "Veg Sand", "Bedrock"))
```

```{r reading in ghaghra data and processing}

ghaghra <- read.csv('/Users/vedikakalra/Documents/WCT/CCF Hydrology Data/Ghaghra/g-sand-training-m25.csv')
ghaghra <- ghaghra%>%
  select(-".geo", -"system.index")
ghaghra$class <- factor(ghaghra$class,
levels = c(1, 2, 3, 4, 5, 6),
labels = c("Fresh Sand", "Curcubit", "Wet Sand", "Gen Agri", "Fallow", "Scrubs"))

```

```{r chambal spectral signature}
long <- pivot_longer(texture, cols = -class, names_to = "band", values_to = "reflectance")
sand_summary <- long%>%
  group_by(class, band)%>%
  summarise(mean_reflectance = mean(reflectance), .groups = "drop")

ggplot(sand_summary, aes(x = band, y = mean_reflectance, color = class, group = class))+
  geom_line()+
  theme_minimal()+
  labs(title = "Spectral Signatures of Sand")+
  scale_color_discrete(labels = c("1" = "fresh alluv", "2" = "sandmine", "3" = "wet sand", "4" = "fallow", "5" = "veg sand", "6" = "rock"))

```

```{r chambal decision tree}
tree_model <- rpart(class~ B11 + B12 + B2 + B3 + B4 + B8 + NDBI + NDMI + MNDWI + NDVI + BCI +
                            NDSI, data = texture, method = 'class')
print(tree_model)
rpart.plot(tree_model,
           main = "Chambal Sand Signature Decision Tree",
           type = 4,
           extra = 104,
           yes.text = "Yes",
           no.text = "No",
           box.palette = "BuBn",
           shadow.col = "gray80",
           border.col = "gray40",
           #branch = 0.5,
           split.cex = 0.85,
           split.font = 2,
           fallen.leaves = TRUE,
           font = 1
           )

plotcp(tree_model)

#########################################

chambal_model <- tree(class~ B11 + B12 + B2 + B3 + B4 + B8 + NDBI + NDMI + MNDWI + NDVI + BCI + contrast 
                      + correlation + dissimilarity + entropy + homogeneity + variance + asm +
                            NDSI, data = texture)
plot(chambal_model)
text(chambal_model, pretty = 0, cex = 0.6)
cv_chambal <- cv.tree(chambal_model, FUN = prune.misclass)
cv_chambal

summary(chambal_model)
plot(cv_chambal$size,
     cv_chambal$dev,
     type = "b",
     xlab = "Tree Size",
     ylab = "CV Misclassification Error")

pruned_chambal <- prune.misclass(chambal_model, best = 6)

plot(pruned_chambal)
text(pruned_chambal, pretty = 0, cex = 0.7)
title("Classification and Regression Tree: Chambal",
      col.main = "grey10",
      font.main = 2,
      cex.main = 0.9,
      adj = 0.6)
summary(pruned_chambal)
max_depth <- max(floor(log2(as.integer(rownames(pruned_chambal$frame)))))
print(max_depth)
print(pruned_chambal)

```

```{r son decision tree}
son_model <- rpart(class~ B11 + B12 + B2 + B3 + B4 + B8 + NDBI + NDMI + MNDWI + NDVI + BCI + HAND + NDWI + SNDVI +
                     asm + contrast + correlation + dissimilarity + entropy + homogeneity + variance +
                            NDSI, data = son, method = 'class')

print(son_model)
rpart.plot(son_model,
           main = "Son Sand Signature Decision Tree",
           type = 4,
           extra = 104,
           yes.text = "Yes",
           no.text = "No")

plotcp(son_model)

prune_son <- prune(son_model, cp = 0.068)
rpart.plot(prune_son, 
           main = "Son Sand Signature Decision Tree",
           type = 4,
           extra = 104,
           yes.text = "Yes",
           no.text = "No",
            box.palette = "BuBn",
           shadow.col = "gray80",
           border.col = "gray40",
           split.cex = 0.85,
           split.font = 2,
           fallen.leaves = TRUE,
           font = 1
           )

print(prune_son)

###################################
son_tree <- tree(class~ B11 + B12 + B2 + B3 + B4 + B8 + NDBI + NDMI + MNDWI + NDVI + BCI + HAND + NDWI + SNDVI +
                     asm + contrast + correlation + dissimilarity + entropy + homogeneity + variance +
                            NDSI, data = son)

cv_son <- cv.tree(son_tree, FUN = prune.misclass)
plot(cv_son$size,
     cv_son$dev,
     type = "b",
     xlab = "Tree Size",
     ylab = "CV Misclassification Error") 

pruned_son <- prune.misclass(son_tree, best = 6)
plot(pruned_son)
text(pruned_son, pretty = 0, cex = 0.7)
title("Decision Tree for Son Classification",
      col.main = "grey10",
      font.main = 2,
      cex.main = 0.9,
      adj = 0.4)
summary(pruned_son)
print(pruned_son)

```

```{r ghaghra decision tree}
ghaghra_model <- rpart(class~ B11 + B12 + B2 + B3 + B4 + B8 + NDBI + NDMI + MNDWI + NDVI + BCI + HAND + NDWI + SNDVI +
                     asm + contrast + correlation + dissimilarity + entropy + homogeneity + variance +
                            NDSI, data = ghaghra, method = 'class')

print(ghaghra_model)
rpart.plot(
  ghaghra_model,
  main = "Ghaghra Sand Signature Decision Tree",
           type = 4,
           extra = 104,
           yes.text = "Yes",
           no.text = "No"
)

plotcp(ghaghra_model)

prune_ghaghra <- prune(ghaghra_model, cp = 0.038)
rpart.plot(prune_ghaghra, 
           main = "Ghaghra Sand Signature Decision Tree",
           type = 4,
           extra = 104,
           yes.text = "Yes",
           no.text = "No",
           box.palette = "BuBn",
           shadow.col = "gray80",
           border.col = "gray40",
           #branch = 0.5,
           split.cex = 0.85,
           split.font = 2,
           fallen.leaves = TRUE,
           font = 1
           )

print(prune_ghaghra)

#################################################

ghaghra_plot <- tree(class~ B11 + B12 + B2 + B3 + B4 + B8 + NDBI + NDMI + MNDWI + NDVI + BCI + HAND + NDWI + SNDVI +
                     asm + contrast + correlation + dissimilarity + entropy + homogeneity + variance +
                            NDSI, data = ghaghra)

cv_ghaghra <- cv.tree(ghaghra_plot, FUN = prune.misclass)
plot(cv_ghaghra$size,
     cv_ghaghra$dev,
     type = "b",
     xlab = "Tree Size",
     ylab = "CV Misclassification Error") 

pruned_ghaghra <- prune.misclass(ghaghra_plot, best = 6)
plot(pruned_ghaghra)
text(pruned_ghaghra, pretty = 0, cex = 0.7)
title("Decision Tree for Ghaghra Classification",
      col.main = "grey10",
      font.main = 2,
      cex.main = 0.9,
      adj = 0.4)
summary(pruned_ghaghra)
print(pruned_ghaghra)


```

```{r importing raster}
raster <- rast('/Users/vedikakalra/Documents/WCT/CCF Hydrology Data/Chambal/c-sand-merge3.tif')
names(raster) <- c("NDVI", "NDBI", "MNDWI", "NDSI", "NDMI", "BCI",
                         "B2", "B3", "B4", "B8", "B11", "B12")

#Checking if the names in the model match that in the raster. Should be TRUE
all(all.vars(tree_model$terms)[-1] %in% names(raster))
```

```{r}
classified <- predict(raster, tree_model, type = "class")

writeRaster(classified, "/Users/vedikakalra/Documents/WCT/CCF Hydrology Data/Chambal/rule-based_output.tif", overwrite = TRUE)
plot(classified, main = "Classified Raster")
global(raster, fun = "range", na.rm = TRUE)   
```

```{r}
supervised <- read.csv("/Users/vedikakalra/Documents/WCT/c-supervised-march23-verification.csv")
supervised <- supervised%>%
  select(-"system.index", -".geo")



supervised$class <- factor(supervised$classID,
                           levels = c(1,2,3,4,5,6,7),
                           labels = c("Shallow water", "Deep water", "Fresh alluvium", "Old alluvium", "Agri veg", "Gen veg", "Bedrock"))
supervised_model <- tree(class~ NDWI, data = supervised) 
plot(supervised_model)
text(supervised_model, pretty = 0, cex = 0.7)
cv_supervised <- cv.tree(supervised_model, FUN = prune.misclass)
plot(cv_supervised)
trim_supervised <- prune.misclass(supervised_model, best = 5)
plot(trim_supervised)
text(trim_supervised, pretty = 0, cex = 0.7)
```

